spring:
    datasource:
        url: jdbc:h2:mem:dbname
        #url: jdbc:h2:mem:development
        username: sa
        password: password
        driver-class-name: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        generate-ddl: true
        #open-in-view: false
        properties:
            jakarta:
                persistence:
                    sharedCache:
                        mode: ALL
    h2:
        console:
            enabled: true

logging:
    level:
        root: INFO
        org.springframework.web: INFO
        org.springframework.security: INFO


application:
    security:
        jwt:
            #TODO not save key! pass by args not hardcoded!
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            expiration: 86400000 # 7 days
            refresh-token:
                expiration: 604800000
server:
    port: 8000